### ISSUE TITLE
Support for aarch64

### ISSUE THREAD

**Issue by j-delvaux** [triton-inference-server/pytriton#26]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I saw in the _known_issues.md_ that only x86-64 is currently supported. Is there any official plan to support aarch64 (e.g. AGX Orin) in a near future ?
Even if not officially supported, is this feasible by changing few things ?

**Describe alternatives you've considered**
None

**Additional context**
No

Thank you and keep up the good work :)

**Comment by piotrm-nvidia** [comment]
## Introduction

Thank you for your feature request. We appreciate your interest in pyTriton and its potential applications on aarch64 devices, such as AGX Orin.

PyTriton relies on the NVIDIA Triton Inference Server binaries, which are currently only available for x86-64 operating systems. This is why pyTriton does not support aarch64 architecture at the moment.

The build script of pyTriton copies these binaries from the official Triton docker image, which you can find in [extract_triton.sh](https://github.com/triton-inference-server/pytriton/blob/main/scripts/extract_triton.sh). Our solution uses directly docker so for ARM build with cross-compilation it must be adapted.

The compilation of Triton is handled by the Triton repository, which contains build scripts and instructions [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/build.html). If you want to try to build Triton for aarch64 yourself, you might need to modify these scripts and resolve any compatibility issues that might arise.

Supporting aarch64 architecture for pyTriton would be a great feature, as it would enable users to leverage the benefits of Triton Inference Server and Python frameworks for high-performance computing and machine learning applications on powerful platforms like AGX Orin. However, it would also require a lot of work and testing to ensure that pyTriton works correctly and efficiently on such devices. We consider in our roadmap adding ARM supports in near future.

If you are interested in contributing to this feature, we would love to hear from you. You can open pull request on the GitHub repository of pyTriton and share your ideas or code with us.

## Qemu ARM64 build

I analyzed pyTriton build scripts and I can use Qemu emulation in docker to build and test pyTriton wheel for ARM.

To use QEMU and Docker for ARM emulation, you need to follow these steps:

- Install the QEMU packages on your x86 machine: `sudo apt-get install qemu binfmt-support qemu-user-static`
- Register the QEMU emulators for ARM architectures: `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes`

**Running build inside arm64 ubuntu 20.4 docker**

1. Start arm docker with access to host docker daemon (don't forget about your folder with pyTriton sources)
   ```bash
   /your_home/pytriton$ docker run -ti --platform linux/arm64 -v /var/run/docker.sock:/var/run/docker.sock -v /your_home/pytriton/:/your_home/pytriton ubuntu:20.04 bash
   ```
1. Inside docker update apt and install packages
    ```bash
    /your_home/pytriton# apt update
    /your_home/pytriton# apt install -y docker-io python3-pip
    ```
1. Install pytriton development dependencies
    ```bash
    /your_home/pytriton# make install-dev
    ```
1. Build pytriton
    ```bash
    /your_home/pytriton# make dist
    ```
1. Install wheel builded locally.
1. Run tests with pytest.

I used this guide with patch below and build wheel for ARM64. It was also possible to run pytest tests from ``tests`` folder so Triton starts and server model in test environment.

## ARM64 compilation patch

This patch adds support for building wheel packages for different architectures and platforms using environment variables. It does the following changes:

- It defines the PLATFORM and ARCH variables in the Makefile and sets their default values to linux/arm64 and aarch64 respectively.
- It modifies the dist and extract-triton tasks in the Makefile to pass the PLATFORM and ARCH variables to the scripts that add libraries to the wheel and extract triton from the docker image.
- It modifies the plat-name setting in the pyproject.toml file to use linux_aarch64 instead of linux_x86_64.
- It modifies the add_libs_to_wheel.sh script to accept the ARCH and PLATFORM variables as arguments and use them to set the TARGET_PLATFORM variable and the --platform option for docker create.
- It modifies the extract_triton.sh script to accept the PLATFORM variable as an argument and use it to set the --platform option for docker create.

```diff
diff --git a/Makefile b/Makefile
index f5cca84..9569fb5 100644
--- a/Makefile
+++ b/Makefile
@@ -39,6 +39,8 @@ PIP_INSTALL := pip install --extra-index-url https://pypi.ngc.nvidia.com
 TRITONSERVER_IMAGE_VERSION = 23.04
 TRITONSERVER_IMAGE_NAME = nvcr.io/nvidia/tritonserver:$(TRITONSERVER_IMAGE_VERSION)-pyt-python-py3
 TRITONSERVER_OUTPUT_DIR = pytriton/tritonserver
+PLATFORM=linux/arm64
+ARCH=aarch64
 
 help:
 	@python -c "$$PRINT_HELP_PYSCRIPT" < $(MAKEFILE_LIST)
@@ -95,14 +97,14 @@ coverage: ## check code coverage quickly with the default Python
 
 dist: clean extract-triton ## builds source and wheel package
 	python3 -m build .
-	find ./dist -iname *-linux*.whl -type f -exec bash ./scripts/add_libs_to_wheel.sh $(TRITONSERVER_IMAGE_NAME) $(TRITONSERVER_OUTPUT_DIR) {} \;
+	find ./dist -iname *-linux*.whl -type f -exec bash ./scripts/add_libs_to_wheel.sh $(TRITONSERVER_IMAGE_NAME) $(TRITONSERVER_OUTPUT_DIR) {} ${ARCH} ${PLATFORM} \;
 	find ./dist -iname *-linux*.whl -type f -delete
 	ls -lh dist
 	twine check dist/*
 
 extract-triton:
 	# changing dst path, change also in clean-build and pyproject.toml
-	bash ./scripts/extract_triton.sh $(TRITONSERVER_IMAGE_NAME) $(TRITONSERVER_OUTPUT_DIR)
+	bash ./scripts/extract_triton.sh $(TRITONSERVER_IMAGE_NAME) $(TRITONSERVER_OUTPUT_DIR) $(PLATFORM)
 
 install: clean extract-triton ## install the package to the active Python's site-packages
 	$(PIP_INSTALL) --upgrade pip
diff --git a/pyproject.toml b/pyproject.toml
index 97b5ce3..08e5086 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -112,7 +112,7 @@ pytriton = [
 [tool.setuptools_scm]
 
 [tool.distutils.bdist_wheel]
-plat-name = "linux_x86_64"
+plat-name = "linux_aarch64"
 
 
 [tool.black]
diff --git a/scripts/add_libs_to_wheel.sh b/scripts/add_libs_to_wheel.sh
index 8a979a8..5683686 100755
--- a/scripts/add_libs_to_wheel.sh
+++ b/scripts/add_libs_to_wheel.sh
@@ -16,7 +16,10 @@
 set -x
 set -e
 
-TARGET_PLATFORM=manylinux_2_31_x86_64
+ARCH=${4}
+PLATFORM=${5}
+
+TARGET_PLATFORM=manylinux_2_31_${ARCH}
 SCRIPTS_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
 
 TRITON_DOCKER_IMAGE="${1}"
@@ -24,7 +27,7 @@ TRITON_LOCAL_DIR=$(realpath "${2}")
 WHEEL_PATH=$(realpath "${3}")
 DIST_DIR="$(dirname "${WHEEL_PATH}")"
 
-DOCKER_CONTAINER_ID=$(docker create --rm -w "${PWD}" "${TRITON_DOCKER_IMAGE}" bash -c "sleep 1h")
+DOCKER_CONTAINER_ID=$(docker create --rm --platform ${PLATFORM} -w "${PWD}" "${TRITON_DOCKER_IMAGE}" bash -c "sleep 1h")
 docker start "${DOCKER_CONTAINER_ID}"
 
 docker exec "${DOCKER_CONTAINER_ID}" mkdir -p "${DIST_DIR}"
diff --git a/scripts/extract_triton.sh b/scripts/extract_triton.sh
index f61e74e..e359992 100755
--- a/scripts/extract_triton.sh
+++ b/scripts/extract_triton.sh
@@ -18,9 +18,11 @@ set -x
 export TRITON_CONTAINER=$1
 
 export TARGET_DIR=$2
+
+export PLATFORM=$3
 rm -rf "${TARGET_DIR}"
 
-export TRITON_CONTAINER_ID=$(docker create --rm "${TRITON_CONTAINER}" bash -c "sleep 1h")
+export TRITON_CONTAINER_ID=$(docker create --platform "${PLATFORM}" --rm "${TRITON_CONTAINER}" bash -c "sleep 1h")
 docker start "${TRITON_CONTAINER_ID}"
 
 mkdir -p "${TARGET_DIR}"/backends
```

**Comment by j-delvaux** [comment]
Hello @piotrm-nvidia,

Just to say a quick thank you for your response :)
I'll look into it. 

I already created a docker image with the Triton server for aarch64 without any issue and it detects correctly the GPU from the AGX Orin.

We'll keep in touch,
Have a nice day

**Comment by piotrm-nvidia** [comment]
ARM is supported from release 0.4.1.
