### ISSUE TITLE
Document pros and cons

### ISSUE THREAD

**Issue by denis-angilella** [triton-inference-server/pytriton#3]
**Is your feature request related to a problem? Please describe.**
Lack of documentation on pros and cons of using PyTriton VS Triton backends directly.

**Describe the solution you'd like**
First, thanks for this library! It fills a gap between writing usual Python code and using Triton. 

I would like to find the answers to the following questions in the documentation:
1. Latency: what is the latency overhead of executing an inference function in PyTriton VS implementing a `TritonPythonModel` with the same code in Python backend?
2. Concurrency: is parallel execution of inference functions limited by Python GIL? If yes, how can this be overcome?
3. Local model or backend: what are the pros and cons of e.g. loading a TensorFlow SavedModel and using it in a inference function VS serving the same model with the Triton TensorFlow backend?
4. Supported backends: how to add more backends to the built-in Triton, f.i. the TensorFlow backend
5. Invoke other models: how can an inference function executes inference requests on other models served by Triton, similarly to [BLS](https://github.com/triton-inference-server/python_backend#business-logic-scripting)?
7. Collocation with other services: is it advised to run other servers (e.g. a JSON-RPC server frontend) or threads (e.g. to reload a data file) in the same "`server.py`" process?
8. External services: is it advised to call external APIs (e.g. to retrieve additional features) from an inference function?

**Describe alternatives you've considered**
Publishing a rationale of why this project was created and a roadmap would answers some of the questions.
Having a forum where such questions can be asked would help too. 

**Additional context**
Thank you in advance!
Feel free to ask if more information is needed.

**Comment by nv-blazejkubiak** [comment]
I hope I will address your questions and concerns. If you have any additional questions or suggestions (especially related to specific cases), please feel free to share them with us.

> 1. Latency: what is the latency overhead of executing an inference function in PyTriton VS implementing a TritonPythonModel with the same code in Python backend?

There is one additional copy of the input and output tensors. During our tests, latency overhead was around 5%, but of course it may vary depending on the ratio between the model size and the IO size.

> 2. Concurrency: is parallel execution of inference functions limited by Python GIL? If yes, how can this be overcome?

Yes, currently inference functions are limited by GIL. If you have multiple PyTriton models (end points) running in parallel, it is better not to run the time-consuming tasks in the inference functions if they are written with the native python code (one model is always executed sequentially batch after batch). Calling the IO or the native code releases GIL, so if you just call a deep-learning framework (there is a lot of c++ under the neath), synchronization on GIL might not be a problem.
If you need real parallelization, at the moment you have to delegate your jobs to subprocesses by yourself.

In near future we have plans to solve this in PyTriton either by adding the possibility to run processes instead of threads or having remote mode that lets connecting to the same Triton server from multiple PyTriton instances (from multiple python script processes).

> 3. Local model or backend: what are the pros and cons of e.g. loading a TensorFlow SavedModel and using it in an inference function VS serving the same model with the Triton TensorFlow backend?

PyTriton is written in python (It is easier to use and deploy, but it has some overhead while processing inference). If you already have your deployment package prepared for TensorFlow backend, probably it is better to stay with that. If you start from scratch, you can spend 15 minutes and run it in PyTriton and check your model latency, efficiency etc. You can always switch to TensorFlow backend when you need that.

> 4. Supported backends: how to add more backends to the built-in Triton, f.i. the TensorFlow backend

There is no option to install additional backends to the built-in Triton. The backend directory passed to Triton is set to "triton-server-folder/backends" located in the python libs folder and it contains python-backend only. In that case it would be a bit hacky to build the other backends by hand and to copy them to the python libs folder. We could consider adding an optional parameter for passing a custom backend folder if that would be really necessary.
Using the other backends would be also possible with remote-mode (described in point 2) where you could connect to the existing triton server that is equipped with all necessary backends, but this option is not available yet.
Can you share your case? That would let us understand how common is your case and what priorities we should add to this kind of feature.

> 5. Invoke other models: how can an inference function executes inference requests on other models served by Triton, similarly to [BLS](https://github.com/triton-inference-server/python_backend#business-logic-scripting)?

Currently BLS is not supported and it is not our top priority feature (in python you can load multiple models and call them as you want).
If you see a scenario where BLS would be really beneficial in PyTriton, we would really like to know such case.

> 6. Collocation with other services: is it advised to run other servers (e.g. a JSON-RPC server frontend) or threads (e.g. to reload a data file) in the same "server.py" process?

From a GIL limitation perspective, it might be better to put it in separate processes. I don't see the other pros/cons - it depends on the specific case.

> 7. External services: is it advised to call external APIs (e.g. to retrieve additional features) from an inference function?

I would say, there is no reason to discourage you from calling external API from inference function if it is necessary. Consider moving them to the initialization stage and use cache mechanisms where possible.
