### ISSUE TITLE
Best practices with ModelClient 

### ISSUE THREAD

**Issue by markbarna** [triton-inference-server/pytriton#32]
This is really just a question around using `ModelClient` in a situation where you expect to send a large number of inference requests over time. 

My use-case is a python service that listens to a RabbitMQ queue for inference requests and then sends a Triton inference call for each message in the queue. Therefore, the service that is using `ModelClient` will be running continuously. My question is whether I should use the context manager `with ModelClient() as client...` for each inference request or if I should instantiate one client object at start-up and keep it open until the service is shut down. I didn't see any examples that didn't use the context manager so I wasn't sure.
Thanks you

**Comment by piotrm-nvidia** [comment]
> 



> This is really just a question around using `ModelClient` in a situation where you expect to send a large number of inference requests over time.
> 
> My use-case is a python service that listens to a RabbitMQ queue for inference requests and then sends a Triton inference call for each message in the queue. Therefore, the service that is using `ModelClient` will be running continuously. My question is whether I should use the context manager `with ModelClient() as client...` for each inference request or if I should instantiate one client object at start-up and keep it open until the service is shut down. I didn't see any examples that didn't use the context manager so I wasn't sure. Thanks you

**Comment by piotrm-nvidia** [comment]
The context manager is a Python feature that allows you to execute some code before and after a block of statements, usually for the purpose of resource management. For example, when you use the context manager with ModelClient, it will automatically create and close the connection with the server, as well as handle any errors that may occur.

However, using the context manager is not mandatory, and you can also create and use a ModelClient object without it. In this case, you can manually create the connection with the server using the `wait_for_model()` method, and close it when you are done using the `close()` method. You will also need to handle any exceptions that may arise from the communication with the server.

Here is an example of a script that keeps a ModelClient object without using the context manager:

```python
# Import ModelClient from PyTriton
from pytriton.client import ModelClient

# Create a ModelClient object with the server URL and model name
client = ModelClient("localhost:8000", "my_model")
# Open connection and wait for model to start for 10 seconds
client.wait_for_model(10)

# Send inference requests and receive responses in a loop
while True:
    # Get an inference request from the RabbitMQ queue
    request = get_request_from_queue()
    
    # Check if the request is valid
    if request is not None:
        # Send the request to the server and get the response
        response = client.infer_sample(request)
        
        # Process the response as needed
        process_response(response)
    else:
        # Break the loop if there are no more requests
        break

# Close the connection with the server
client.close()
```

I hope this example helps you understand how to use ModelClient without the context manager. However, I would also like to know more about your exact scenario and why you prefer this approach over using the context manager. Is there any specific reason or benefit that you expect from keeping a ModelClient object open for a long time? I am curious to hear your thoughts on this.

**Comment by piotrm-nvidia** [comment]
Hi @markbarna ,

Thank you for providing more details about your scenario. I appreciate your feedback and I will try to update my answer accordingly.

Using a ModelClient object without the context manager has some advantages and disadvantages compared to using the context manager for each inference request, which I will explain below.

Using a ModelClient object without the context manager has the advantage of avoiding the overhead of creating and closing the connection for each request, which may improve the inference latency and throughput. Moreover, this approach may be more efficient because each new instance of ModelClient is downloading the model configuration and runs requests to check if the server is alive and the model is ready.

On the other hand, using the context manager for each inference request has the advantage of ensuring that the connection with the server is always fresh and reliable. This may prevent some potential issues such as connection timeouts, stale connections, or memory leaks.

In summary, both approaches have their own benefits and drawbacks, and you may need to experiment with both to find out which one suits your needs better. However, based on your scenario, it seems that using a ModelClient object without the context manager may be more suitable for you, as long as you ensure that the connection with the server is stable and secure, and that you manage your client resources properly. 

We are considering new feature for ModelClient that will allow to serialize and deserialize model configuration. This will allow to create ModelClient object with only connection options and model name, and then load model configuration from file or string. This will allow to avoid downloading model configuration and checking if model is ready for each ModelClient object. This will also allow to create ModelClient object without context manager and without manually calling `wait_for_model()` method. This feature is not yet implemented, but we are considering it for future releases.

I hope this updated comparison helps you make an informed decision. Please let me know if you have any further questions or suggestions regarding new features.
