### ISSUE TITLE
What is the proxy backend in pytriton?

### ISSUE THREAD

**Issue by HJH0924** [triton-inference-server/pytriton#53]
In Triton, the backend refers to the several types recorded in this [link](https://github.com/triton-inference-server/backend/blob/main/docs/backend_platform_support_matrix.md), while in the [architecture of pytriton](https://github.com/triton-inference-server/pytriton/blob/main/README.md#architecture), proxy backend is mentioned. What is this?

**Comment by piotrm-nvidia** [comment]
The Triton Inference Server's architecture and the concept of a "proxy backend" in PyTriton can be understood by examining their respective documentation and usage.

While the Triton Inference Server's backend refers to the actual implementations executing the models, the "Proxy Backend" in the context of PyTriton appears to be a mechanism within PyTriton for handling data transfer between Python callbacks and the Triton Server.

1. **Triton Inference Server Backends**: According to the [Triton Backend](https://github.com/triton-inference-server/backend/blob/main/README.md) readme, a backend in Triton is the implementation that executes a model. This can be a wrapper around a deep learning framework like PyTorch, TensorFlow, TensorRT, or ONNX, or it can be custom C/C++ logic performing operations like image pre-processing. Each backend must implement the Triton Backend API, allowing Triton to send requests to the backend for execution and the backend to communicate with Triton. PyTriton uses [Python backend](https://github.com/triton-inference-server/python_backend), which runs server for PyTriton proxy written in Python. It is generic and can be used for any framework, because it just handles input/output tensors and passes them to Python callbacks to [Inference Callable](https://triton-inference-server.github.io/pytriton/latest/inference_callables/).

2. **PyTriton Proxy Backend**: The reference to "Proxy Backend" in the PyTriton context, as mentioned in the [PyTriton high level design](https://triton-inference-server.github.io/pytriton/latest/high_level_design/), relates to the mechanism for passing input/output tensors between processes using shared memory. PyTriton initializes a certain amount of shared memory for this Proxy Backend to facilitate this data transfer. Inference Callable exists in your process, but Triton spawns another process for Python backend and there our generic code with Proxy Backend waits for inference requests. You define Python function and it must be called by Triton, when data is ready.

Is this explanation sufficient? If not, please let me know and I will try to clarify further.

**Comment by HJH0924** [comment]
You explained it very clearly and I understood, thank you very much!
